language: php

php:
  - 5.6
  - 7.0
  - 7.1


install:
- travis_retry composer install --no-interaction --no-suggest

script:
- vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox